# Write your code here :-)
print("===============================================================================")
print("                        HELLO WORLD                                              ")
print("                      by Ryan Anderson                                          ")
print("===============================================================================")
print("")
print("yes")
name = input("What's your name?    ")
print(f"Hello {name}")